export const INTEGRATION_PROVIDERS = {
  cal: {
    key: 'cal',
    name: 'Cal.com',
    category: 'During Call',
    oauth: {
      authorizationUrl: 'https://app.cal.com/oauth/authorize',
      tokenUrl: 'https://api.cal.com/oauth/token',
      scope: ['users.read', 'bookings.read', 'bookings.write'],
      clientIdEnv: 'CAL_CLIENT_ID',
      clientSecretEnv: 'CAL_CLIENT_SECRET',
      redirectUriEnv: 'CAL_REDIRECT_URI',
    },
    apiBaseUrlEnv: 'CAL_API_BASE_URL',
    syncEndpoint: '/v2/me',
  },
  calendly: {
    key: 'calendly',
    name: 'Calendly',
    category: 'During Call',
    oauth: {
      authorizationUrl: 'https://auth.calendly.com/oauth/authorize',
      tokenUrl: 'https://auth.calendly.com/oauth/token',
      scope: ['default'],
      clientIdEnv: 'CALENDLY_CLIENT_ID',
      clientSecretEnv: 'CALENDLY_CLIENT_SECRET',
      redirectUriEnv: 'CALENDLY_REDIRECT_URI',
    },
    apiBaseUrlEnv: 'CALENDLY_API_BASE_URL',
    syncEndpoint: '/users/me',
  },
  custom_api: {
    key: 'custom_api',
    name: 'Custom API',
    category: 'During Call',
    oauth: null,
  },
  salesforce: {
    key: 'salesforce',
    name: 'Salesforce',
    category: 'Post Call',
    oauth: {
      authorizationUrl: 'https://login.salesforce.com/services/oauth2/authorize',
      tokenUrl: 'https://login.salesforce.com/services/oauth2/token',
      scope: ['api', 'refresh_token', 'offline_access'],
      clientIdEnv: 'SALESFORCE_CLIENT_ID',
      clientSecretEnv: 'SALESFORCE_CLIENT_SECRET',
      redirectUriEnv: 'SALESFORCE_REDIRECT_URI',
    },
    apiBaseUrlEnv: 'SALESFORCE_INSTANCE_URL',
    syncEndpoint: '/services/data/v60.0/sobjects/Lead/describe',
  },
  google_calendar: {
    key: 'google_calendar',
    name: 'Google Calendar',
    category: 'During Call',
    oauth: {
      authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scope: ['https://www.googleapis.com/auth/calendar', 'https://www.googleapis.com/auth/userinfo.email', 'offline_access'],
      clientIdEnv: 'GOOGLE_CLIENT_ID',
      clientSecretEnv: 'GOOGLE_CLIENT_SECRET',
      redirectUriEnv: 'GOOGLE_REDIRECT_URI',
      extraParams: { access_type: 'offline', prompt: 'consent' },
    },
    apiBaseUrlEnv: 'GOOGLE_API_BASE_URL',
    syncEndpoint: '/calendar/v3/users/me/calendarList',
  },
  google_sheets: {
    key: 'google_sheets',
    name: 'Google Sheets',
    category: 'Post Call',
    oauth: {
      authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
      tokenUrl: 'https://oauth2.googleapis.com/token',
      scope: ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive.readonly', 'offline_access'],
      clientIdEnv: 'GOOGLE_CLIENT_ID',
      clientSecretEnv: 'GOOGLE_CLIENT_SECRET',
      redirectUriEnv: 'GOOGLE_REDIRECT_URI',
      extraParams: { access_type: 'offline', prompt: 'consent' },
    },
    apiBaseUrlEnv: 'GOOGLE_API_BASE_URL',
    syncEndpoint: '/drive/v3/files?q=mimeType%3D%27application%2Fvnd.google-apps.spreadsheet%27&pageSize=10',
  },
  slack: {
    key: 'slack',
    name: 'Slack',
    category: 'During Call',
    oauth: {
      authorizationUrl: 'https://slack.com/oauth/v2/authorize',
      tokenUrl: 'https://slack.com/api/oauth.v2.access',
      scope: ['chat:write', 'channels:read', 'groups:read', 'users:read', 'incoming-webhook'],
      clientIdEnv: 'SLACK_CLIENT_ID',
      clientSecretEnv: 'SLACK_CLIENT_SECRET',
      redirectUriEnv: 'SLACK_REDIRECT_URI',
    },
    apiBaseUrlEnv: 'SLACK_API_BASE_URL',
    syncEndpoint: '/auth.test',
    webhookSigningSecretEnv: 'SLACK_SIGNING_SECRET',
  },
  hubspot: {
    key: 'hubspot',
    name: 'HubSpot',
    category: 'Post Call',
    oauth: {
      authorizationUrl: 'https://app.hubspot.com/oauth/authorize',
      tokenUrl: 'https://api.hubapi.com/oauth/v1/token',
      scope: ['crm.objects.contacts.read', 'crm.objects.contacts.write', 'crm.objects.deals.read', 'crm.objects.deals.write'],
      clientIdEnv: 'HUBSPOT_CLIENT_ID',
      clientSecretEnv: 'HUBSPOT_CLIENT_SECRET',
      redirectUriEnv: 'HUBSPOT_REDIRECT_URI',
    },
    apiBaseUrlEnv: 'HUBSPOT_API_BASE_URL',
    syncEndpoint: '/crm/v3/objects/contacts?limit=1',
  },
  genesys: {
    key: 'genesys',
    name: 'Genesys',
    category: 'During Call',
    oauth: {
      authorizationUrl: 'https://login.{region}/oauth/authorize',
      tokenUrl: 'https://login.{region}/oauth/token',
      scope: ['conversation:read', 'conversation:write', 'routing:queue:read'],
      clientIdEnv: 'GENESYS_CLIENT_ID',
      clientSecretEnv: 'GENESYS_CLIENT_SECRET',
      redirectUriEnv: 'GENESYS_REDIRECT_URI',
    },
    apiBaseUrlEnv: 'GENESYS_API_BASE_URL',
    syncEndpoint: '/api/v2/users/me',
  },
};

export const INTEGRATION_ORDER = [
  'cal',
  'calendly',
  'custom_api',
  'salesforce',
  'google_calendar',
  'google_sheets',
  'slack',
  'hubspot',
  'genesys',
];

export const INTEGRATION_NAME_TO_KEY = Object.fromEntries(
  Object.values(INTEGRATION_PROVIDERS).map((provider) => [provider.name.toLowerCase(), provider.key])
);